### ISSUE TITLE
无法递归解析函数

### ISSUE THREAD

**Issue by fexcode** [Xnors/Facro#1]
无法递归解析函数

![image](https://github.com/user-attachments/assets/0e863fc0-32ba-43dd-97bd-043e9967b1cd)

![image](https://github.com/user-attachments/assets/46a63e24-d0bc-41f3-b22c-938f072fc20a)

内部函数并没有被解析!!!

**Comment by fexcode** [comment]
ok

**Comment by BaiChuanByte** [comment]
It is fix already
